In [2]:
import numpy as np

In [3]:
arr = np.array([4,3,4,5,6,72,3,3,455,5,6,6])

In [4]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [5]:
np.sort(arr)

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

where the data placed we can find it

In [6]:
np.searchsorted(arr,34)

12

In [7]:
arr1 = np.array([0,345,454,0,0,0,0,0,])

In [8]:
np.count_nonzero(arr1)

2

In [9]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [10]:
np.where(arr>6)

(array([5, 8], dtype=int64),)

In [12]:
np.extract(arr>6,arr)

array([ 72, 455])

In [13]:
arr.byteswap()

array([  67108864,   50331648,   67108864,   83886080,  100663296,
       1207959552,   50331648,   50331648, -956235776,   83886080,
        100663296,  100663296])

copy- make different space 


In [14]:
a = np.copy(arr)

copy refrence and change value by refrence or change value at original index


In [15]:
b= arr.view()

In [16]:
b

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [17]:
b[0]=0

In [18]:
b

array([  0,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [19]:
a

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [20]:
arr

array([  0,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [21]:
import numpy.matlib as nm

In [22]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [23]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Linear Algebra

In [24]:
arr1= np.random.randint([[2,3], [4,5]])

In [25]:
arr2 = np.random.randint([[5,3], [2,5]])

In [26]:
np.dot(arr1,arr2)

array([[0, 8],
       [0, 4]])

In [27]:
arr1@arr2

array([[0, 8],
       [0, 4]])

In [28]:
arr1

array([[1, 2],
       [3, 1]])