# **<span style= 'color:seagreen'>Numpy</span>**

### **What is numpy?**

Numpy is the fundamental package for scientific computing in Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebrea, basic statistical operations, random simulation and much more.

All the core of the Numpy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### **Numpy Arrays Vs Python Sequences**
- NumPy arrays have a fixed size at creation, unlike Python lists(which can grow dynamically).Changing the size of an ndarray
will create a new array and delete the original.
- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.
- NumPy arrays facillitate advanced mathematical and other types of operation on large numbers of data. Typically, such opertations are executed more effciently and with less code than is possible using Python's built-in sequences.
- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays, through these typicallly support python-sequence input, they convert such input to NumPy arrays prior to processing and they often output NumPy arrays.

### **<span style = 'color : magenta'>Creating Numpy Arrays</span>**

In [3]:
# np.array
import numpy as np


In [3]:
# create numpy 1D array
a = np.array([1, 2, 3])
print(a)


[1 2 3]


In [4]:
# type of array
print(type(a))


<class 'numpy.ndarray'>


In [6]:
# create 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)


[[1 2 3]
 [4 5 6]]


In [7]:
# create 3D array
c = np.array([[[1, 2], [3, 4]], [[5, 6], [6, 7]]])
print(c)


[[[1 2]
  [3 4]]

 [[5 6]
  [6 7]]]


In [9]:
# float datatype
d = np.array([1, 2, 3], dtype=float)
print(d)


[1. 2. 3.]


In [11]:
# bool datatype
np.array([1, 2, 3], dtype=bool)


array([ True,  True,  True])

In [12]:
# complex datatype
np.array([1, 2, 3], dtype=complex)


array([1.+0.j, 2.+0.j, 3.+0.j])

In [13]:
# np.arange
np.arange(1, 11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(1, 11, 2)


array([1, 3, 5, 7, 9])

In [15]:
# np.reshape
np.arange(1, 11).reshape(5, 2)


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [16]:
np.arange(1, 11).reshape(2, 5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
# study error
np.arange(1, 11).reshape(5, 5)


ValueError: cannot reshape array of size 10 into shape (5,5)

In [18]:
# np.ones -> every item is 1
# default array is float
np.ones((3, 4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
# np.zeros -> every item is 0
np.zeros((4, 2))


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
# np.random
np.random.random((3, 4))


array([[0.85032095, 0.67623376, 0.74863953, 0.3381394 ],
       [0.24380273, 0.70702724, 0.22450031, 0.54841072],
       [0.17541142, 0.65340015, 0.32233203, 0.70954878]])

In [25]:
# np.linspace
# -10 is lower range , 10 is upper range and 20 is number of item to generate
np.linspace(-10, 10, 20)


array([-10.        ,  -8.94736842,  -7.89473684,  -6.84210526,
        -5.78947368,  -4.73684211,  -3.68421053,  -2.63157895,
        -1.57894737,  -0.52631579,   0.52631579,   1.57894737,
         2.63157895,   3.68421053,   4.73684211,   5.78947368,
         6.84210526,   7.89473684,   8.94736842,  10.        ])

In [27]:
# np.identity -> diagonal items is 1 and rest of item is 0
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.identity(3, dtype=int)


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### **<span style = 'color: purple'>  Array Attributes</span>**

In [29]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)

In [34]:
print('a1: \n', a1)
print('a2: \n', a2)
print('a3: \n', a3)


a1: 
 [0 1 2 3 4 5 6 7 8 9]
a2: 
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
a3: 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [38]:
# ndim -> number of dimensions
print('a1: ', a1.ndim)
print('a2: ', a2.ndim)
print('a3: ', a3.ndim)


a1:  1
a2:  2
a3:  3


In [40]:
# shape -> how many rows and columns
print('a1: ', a1.shape)
a1
# 10 rows

a1:  (10,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
print('a2: ', a2.shape)
a2
# 3 rows 2 columns


a2:  (3, 4)


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [44]:
print('a3: ', a3.shape)
a3
'''first 2 describe how many 2D array and second and third to describe how many rows and 
columns'''


a3:  (2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [46]:
# size -> number of items
print(a1.size)
a1


10


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
print(a2.size)
a2


12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [48]:
print(a3.size)
a3


8


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [52]:
# itemsize -> every item how many size occupy in memory
# int32 -> 4  and int64-> 8  same as float
a1.itemsize


4

In [50]:
a2.itemsize


8

In [51]:
a3.itemsize


4

In [53]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int32
float64
int32


### **<span style = 'color : green'>Changing Datatype</span>**

In [56]:
# astype
print(a2.astype(np.int32))
a2.dtype


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


dtype('float64')

### **<span style = 'color:brown'>Array Operations</span>**

In [57]:
a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(12, 24).reshape(3, 4)

print('a1: \n', a1)
print('a2: \n', a2)


a1: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a2: 
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [59]:
# scaler operations
# --> arithmetic <--

# every item multiply by 2
a1 * 2


array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [61]:
# square of every item
a1 ** 2


array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int32)

In [62]:
# relational

# check every item 
a2 > 5


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [63]:
a2 > 15


array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [64]:
a2 == 15


array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [65]:
# vector operation
# shape must be equal -> a1.shape = a2.shape
a1 + a2


array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [68]:
a2 ** a1


array([[         1,         13,        196,       3375],
       [     65536,    1419857,   34012224,  893871739],
       [-169803776, -288903179, -154967040, 1328067399]], dtype=int32)

### **<span style = 'color: red'>Array Functions</span>**

In [69]:
a1 = np.random.random((3, 3))
a1 = np.round(a1*100)
a1


array([[51., 36., 50.],
       [10.,  5., 27.],
       [ 8., 41., 88.]])

In [73]:
# max/min/sum/prod
print('Max: ', np.max(a1))  # max number in array
print('Min: ', np.min(a1))  # min number in array
print('Sum: ', np.sum(a1))  # sum of all number of array
print('Product: ', np.prod(a1))  # product of all number of array


Max:  88.0
Min:  5.0
Sum:  316.0
Product:  3577115520000.0


In [75]:
# 0 --> col and 1 --> row
# maximum item of every row
print(a1)
np.max(a1, axis=1)


[[51. 36. 50.]
 [10.  5. 27.]
 [ 8. 41. 88.]]


array([51., 27., 88.])

In [76]:
# minimum item of every row
print(a1)
np.min(a1, axis=1)


[[51. 36. 50.]
 [10.  5. 27.]
 [ 8. 41. 88.]]


array([36.,  5.,  8.])

In [78]:
# product of row
np.prod(a1, axis=1)


array([91800.,  1350., 28864.])

In [77]:
# minimum row of every columns
print(a1)
np.max(a1, axis=0)


[[51. 36. 50.]
 [10.  5. 27.]
 [ 8. 41. 88.]]


array([51., 41., 88.])

In [79]:
# mean/ median/ std/ var
np.mean(a1)


35.111111111111114

In [80]:
# row and column of mean
np.mean(a1, axis=0)


array([23.        , 27.33333333, 55.        ])

In [81]:
# median -> you can find row and colomn vise
np.median(a1)


36.0

In [82]:
np.median(a1, axis=0)


array([10., 36., 50.])

In [83]:
# standard deviation
np.std(a1)


25.044158531346383

In [84]:
# variance
np.var(a1)


627.2098765432098

In [85]:
# trignometric function
np.sin(a1) 
# same for cos , tan ...


array([[ 0.67022918, -0.99177885, -0.26237485],
       [-0.54402111, -0.95892427,  0.95637593],
       [ 0.98935825, -0.15862267,  0.0353983 ]])

In [87]:
# dot product

a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(12, 24).reshape(4, 3)

print('a2: \n', a2)
print('a3: \n', a3)


a2: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a3: 
 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [89]:
''' (row1, col1) (row2, col2) -> row1 = col2 and col1 = row2 if this condition true then 
we apply dot product'''
np.dot(a2, a3)


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [90]:
# log and exponents
np.log(a1)


array([[3.93182563, 3.58351894, 3.91202301],
       [2.30258509, 1.60943791, 3.29583687],
       [2.07944154, 3.71357207, 4.47733681]])

In [91]:
np.exp(a1)


array([[1.40934908e+22, 4.31123155e+15, 5.18470553e+21],
       [2.20264658e+04, 1.48413159e+02, 5.32048241e+11],
       [2.98095799e+03, 6.39843494e+17, 1.65163625e+38]])

In [92]:
# round/ floor / ceil

np.random.random((2, 3))*100
# all are float

array([[59.04094484, 32.17821075, 11.55951977],
       [ 4.7255809 , 47.88422335,  0.38452897]])

In [94]:
np.round(np.random.random((2, 3))*100)
# nearest integer -> roundoff

array([[91., 10., 61.],
       [66.,  5., 33.]])

In [95]:
'''lets example - number is 6.9 then floor convert into 6 '''
np.floor(np.random.random((2, 3))*100)


array([[90., 41., 14.],
       [97.,  8., 79.]])

In [96]:
'''lets example - number is 6.1 then ceil convert into 7'''
np.ceil(np.random.random((2, 3))*100)


array([[81., 51., 58.],
       [79., 81., 99.]])

### **<span style = 'color:magenta'>Indexing and Slicing</span>**

In [100]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)

print('a1: \n', a1)
print('a2: \n', a2)
print('a3: \n', a3)


a1: 
 [0 1 2 3 4 5 6 7 8 9]
a2: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a3: 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [104]:
# indexing
print(a1)
print('last index number: ', a1[-1])


[0 1 2 3 4 5 6 7 8 9]
last index number:  9


In [105]:
print(a1)
print('first number of array : ', a1[0])


[0 1 2 3 4 5 6 7 8 9]
first number of array :  0


In [107]:
# 2D 
print(a2)              
print('extracting 6 :', a2[1, 2])   #   a2[row number, column number]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
extracting 6 : 6


In [121]:
# 3D
print(a3)
print('extracting 5 :', a3[1, 0, 1]) # a3[2D array number, row , column]


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
extracting 5 : 5


In [123]:
# slicing
a1
print(a1[2:5])


[2 3 4]


In [130]:
# extracting row
print(a2, '\n\n extracting first row:')
a2[0, :]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

 extracting first column:


array([0, 1, 2, 3])

In [133]:
# extracting column
print(a2, '\n\n extracting first column:')
a2[:, 0]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

 extracting first column:


array([0, 4, 8])

In [134]:
# extracting 5 6 and 9 10
a2[1:3, 1:3]    #a2[start row: end row, start col : end col]


array([[ 5,  6],
       [ 9, 10]])

In [139]:
# extracting corners
a2[::2, ::3] 

# a2[start row : end row : skip row, start col, end col: skip col] 

array([[ 0,  3],
       [ 8, 11]])

In [140]:
# extracting [1, 3],[9, 11]
a2[::2, 1::2]


array([[ 1,  3],
       [ 9, 11]])

In [143]:
# extracting [4, 7]
a2[1, ::3]


array([4, 7])

In [146]:
# 3D array
a3 = np.arange(27).reshape(3, 3, 3)
a3


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [154]:
# extract first and last array in 3D
a3[::2]


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [160]:
# first 2D array of 2nd row
a3[0, 1, :]
# a3[start number of 2D array : end no.of 2D array,star row:end row, start col:end col]


array([3, 4, 5])

In [163]:
# extracting [10, 13, 16]
a3[1, :, 1]


array([10, 13, 16])

In [165]:
# extracting ([[22, 23],[25, 26]])
a3[2, 1:, 1:]


array([[22, 23],
       [25, 26]])

In [174]:
#  extracting ([[0,2], [18, 20]])
a3[::2, 0, ::2]


array([[ 0,  2],
       [18, 20]])

### **<span style = 'color: maroon'>Iterating</span>**

In [175]:
a1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [176]:
for i in a1:
    print(i)


0
1
2
3
4
5
6
7
8
9


In [177]:
# for 2D
for i in a2:
    print(i) #every time 1 row printing


[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [178]:
# for 3D
for i in a3:
    print(i)  # every time one 2D array printing


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [180]:
# print all the number of 3D array
for i in np.nditer(a3):
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### **<span style = 'color:blue'>Reshaping</span>**

In [181]:
a3 = np.arange(27).reshape(3, 3, 3)
a3


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [183]:
# transpose
print(a2)
np.transpose(a2)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [184]:
# another syntax of transpose
a2.T


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [185]:
# ravel -> convert multidimensional array into 1D
a3.ravel()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### **<span style = 'color: seagreen'>Stacking</span>**

In [189]:
# horizontal stacking
a4 = np.arange(12).reshape(3, 4)
a5 = np.arange(12, 24).reshape(3, 4)
print('a4 :\n', a4)
print('a5 :\n', a5)


a4 :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a5 :
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [190]:
np.hstack((a4, a5))


array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [191]:
np.hstack((a4, a5, a5, a4))


array([[ 0,  1,  2,  3, 12, 13, 14, 15, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23, 20, 21, 22, 23,  8,  9, 10, 11]])

In [192]:
# vertical stack
np.vstack((a4, a5))


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### **Splitting**

In [193]:
# horizontal splitting
np.hsplit(a4, 2) # 2 means  split 2D array in 2 equal parts


[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [194]:
# vertical splitting
np.vsplit(a5, 3)


[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [1]:
arr = [5, 9, 9, 10, 11, 12, 12, 3, 4]

In [4]:
len(arr)

9

In [7]:
arr[1:4]

[9, 9, 10]