# **<span style = 'color: seagreen'>NumPy Tricks</span>**

### **np.sort**

In [54]:
# code
import numpy as np
a = np.random.randint(1, 100, 15)
b = np.random.randint(1, 100, 24).reshape(6, 4)

print('a:', a)
print('b: \n', b)


a: [86 96 63 51 48 21 96 80 57 51 45 86  5 71 15]
b: 
 [[67 39 68 79]
 [92 23 34 95]
 [49 13 99 75]
 [58 79 12 85]
 [42 84 17 40]
 [92 60 22 95]]


In [2]:
np.sort(a)


array([ 5,  6,  8, 11, 25, 28, 29, 39, 44, 50, 51, 61, 68, 74, 78])

In [3]:
# sort rows
np.sort(b)


array([[ 2,  9, 59, 61],
       [ 7, 27, 27, 55],
       [31, 86, 89, 95],
       [ 5, 33, 71, 78],
       [ 4, 15, 37, 41],
       [ 4, 31, 43, 92]])

In [5]:
# sort columns
np.sort(b, axis=0)


array([[ 2, 27,  4,  4],
       [33, 41,  9,  5],
       [37, 43, 27,  7],
       [55, 59, 31, 15],
       [86, 78, 31, 61],
       [92, 89, 71, 95]])

In [6]:
# sort in descending order
np.sort(a)[::-1]


array([78, 74, 68, 61, 51, 50, 44, 39, 29, 28, 25, 11,  8,  6,  5])

### **<span style = 'color:#810CA8'>np.append</span>**
The numpy.append() append values along the mentioned axis at the end of the array

In [7]:
# code
np.append(a, 200)


array([ 78,  28,  29,  25,   5,  68,  74,   6,  39,  61,   8,  11,  51,
        44,  50, 200])

In [9]:
np.append(b, np.random.random((b.shape[0], 1)), axis=1)


array([[ 2.        , 59.        ,  9.        , 61.        ,  0.67190434],
       [55.        , 27.        , 27.        ,  7.        ,  0.46483624],
       [86.        , 89.        , 31.        , 95.        ,  0.83888643],
       [33.        , 78.        , 71.        ,  5.        ,  0.78224179],
       [37.        , 41.        ,  4.        , 15.        ,  0.81836621],
       [92.        , 43.        , 31.        ,  4.        ,  0.21444818]])

### **<span style = 'color : #FB2576'>np.concatenate</span>**
numpy.concatenate() function concatenate a sequence of arrays along an existing axis

In [10]:
c = np.arange(6).reshape(2, 3)
d = np.arange(6, 12).reshape(2, 3)

print('c: \n', c)
print('d: \n', d)


c: 
 [[0 1 2]
 [3 4 5]]
d: 
 [[ 6  7  8]
 [ 9 10 11]]


In [11]:
# concatenate -> row
np.concatenate((c, d), axis=0)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
# concatenate -> column
np.concatenate((c, d), axis=1)


array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### **<span style = 'color:#ED5107'>np.unique</span>**
With the help of np.unique() method, we can get the unique values from an array given as paramerter in np.unique() method.

In [14]:
# code
e = np.array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])
f = np.array([[1, 2, 3, 1], [1, 2, 3, 2]])

print('e: ', e)
print('f:\n', f)


e:  [1 1 2 2 3 3 4 4 5 5 6 6]
f:
 [[1 2 3 1]
 [1 2 3 2]]


In [16]:
np.unique(e)


array([1, 2, 3, 4, 5, 6])

### **<span style = 'color:#87431D'>np.expand_dims</span>**
with the help of numpy.expand_dim() method, we can get the expanded dimensions of an array

In [17]:
# code
np.expand_dims(a, axis=1)


array([[78],
       [28],
       [29],
       [25],
       [ 5],
       [68],
       [74],
       [ 6],
       [39],
       [61],
       [ 8],
       [11],
       [51],
       [44],
       [50]])

In [18]:
np.expand_dims(a, axis=0)


array([[78, 28, 29, 25,  5, 68, 74,  6, 39, 61,  8, 11, 51, 44, 50]])

### **np.where**
The np.where() function returns the indices of elements in an input array where the given condition is satisfied.

In [19]:
np.where(a > 50) #index position


(array([ 0,  5,  6,  9, 12], dtype=int64),)

In [20]:
# replace all values > 50 with 0
np.where(a > 50, 0, a)


array([ 0, 28, 29, 25,  5,  0,  0,  6, 39,  0,  8, 11,  0, 44, 50])

In [21]:
# all even number replace with 0
np.where(a % 2 == 0, 0, a)


array([ 0,  0, 29, 25,  5,  0,  0,  0, 39, 61,  0, 11, 51,  0,  0])

### **np.argmax**
The np.argmax() function returns indices of the max element of the array in a particular axis.

In [26]:
print(a)
np.argmax(a)


[34  4 62 12 22 71 20 73 33 85 96 67 85 13 43]


10

In [28]:
# row -> max value index
print(b)
np.argmax(b, axis=1)


[[33 70 35  9]
 [91 91 13 88]
 [72 11 61 54]
 [20 47 57 35]
 [87 83 27 20]
 [34 53 33 58]]


array([1, 0, 0, 2, 0, 3], dtype=int64)

In [29]:
# column -> max value index
np.argmax(b, axis=0)


array([1, 1, 2, 1], dtype=int64)

In [31]:
# np.argmin
print(a)
np.argmin(a)


[34  4 62 12 22 71 20 73 33 85 96 67 85 13 43]


1

### **np.cumsum**
np.cumsum() function is used when we want to compute the comulative sum of array elements over a given axis.

In [33]:
# 34, 34+4= 38, 38+62=100, 100+12 = 112,...
print(a)
np.cumsum(a)


[34  4 62 12 22 71 20 73 33 85 96 67 85 13 43]


array([ 34,  38, 100, 112, 134, 205, 225, 298, 331, 416, 512, 579, 664,
       677, 720], dtype=int32)

In [34]:
print('b:\n', b)

np.cumsum(b, axis=1)
# add row vise -> 
'''[[33, 33+70=103, 103+35=138, 138+9=147]
    [91, 91+91=182, 182+13=195, 195+88=283]
    ...]
'''

b:
 [[33 70 35  9]
 [91 91 13 88]
 [72 11 61 54]
 [20 47 57 35]
 [87 83 27 20]
 [34 53 33 58]]


array([[ 33, 103, 138, 147],
       [ 91, 182, 195, 283],
       [ 72,  83, 144, 198],
       [ 20,  67, 124, 159],
       [ 87, 170, 197, 217],
       [ 34,  87, 120, 178]], dtype=int32)

In [35]:
# np.cumprod
print(a)
np.cumprod(a)
# [34, 34*4=136, ...]

[34  4 62 12 22 71 20 73 33 85 96 67 85 13 43]


array([         34,         136,        8432,      101184,     2226048,
         158049408, -1133979136, -1176098304,  -156538368,  -420859392,
       -1747795968, -1138212864,  2036154368,   700203008,    43958272],
      dtype=int32)

### **np.percentile()**
np.percentile() function used to compute the nth percentile of the given data (array elements)along the specified axis.

In [38]:
print(a)

print(np.percentile(a, 100))  # MAXIMUM

print(np.percentile(a, 0))  # minimum

print(np.percentile(a, 50))  # medimum


[34  4 62 12 22 71 20 73 33 85 96 67 85 13 43]
96.0
4.0
43.0


### **np.histogram**
numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

In [39]:
# frequency count
print(a)
np.histogram(a, bins=[0, 10, 30, 40, 50, 60, 70, 80, 90, 100])


[34  4 62 12 22 71 20 73 33 85 96 67 85 13 43]


(array([1, 4, 2, 1, 0, 2, 2, 2, 1], dtype=int64),
 array([  0,  10,  30,  40,  50,  60,  70,  80,  90, 100]))

### **np.corrcoef**
Return Pearson product-moment correlation coefficients.

In [40]:
salary = np.array([20000, 40000, 25000, 35000, 60000])
experience = np.array([1, 3, 2, 4, 2])
np.corrcoef(salary, experience)


array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### **np.isin**

In [51]:
# code
print(a)

item = [10, 20, 30, 40, 50, 96, 70, 80, 90, 43]

a[np.isin(a, item)]


[34  4 62 12 22 71 20 73 33 85 96 67 85 13 43]


array([20, 96, 43])

### **np.flip**
The np.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

In [52]:
# code
print(a)

np.flip(a)


[34  4 62 12 22 71 20 73 33 85 96 67 85 13 43]


array([43, 13, 85, 67, 96, 85, 33, 73, 20, 71, 22, 12, 62,  4, 34])

In [55]:
print('b: \n', b)
np.flip(b)
# flip both row and col

b: 
 [[67 39 68 79]
 [92 23 34 95]
 [49 13 99 75]
 [58 79 12 85]
 [42 84 17 40]
 [92 60 22 95]]


array([[95, 22, 60, 92],
       [40, 17, 84, 42],
       [85, 12, 79, 58],
       [75, 99, 13, 49],
       [95, 34, 23, 92],
       [79, 68, 39, 67]])

In [56]:
# flip only row
print('b:\n', b)

np.flip(b, axis=1)


b:
 [[67 39 68 79]
 [92 23 34 95]
 [49 13 99 75]
 [58 79 12 85]
 [42 84 17 40]
 [92 60 22 95]]


array([[79, 68, 39, 67],
       [95, 34, 23, 92],
       [75, 99, 13, 49],
       [85, 12, 79, 58],
       [40, 17, 84, 42],
       [95, 22, 60, 92]])

In [57]:
# flip only col
print('b:\n', b)

np.flip(b, axis=0)


b:
 [[67 39 68 79]
 [92 23 34 95]
 [49 13 99 75]
 [58 79 12 85]
 [42 84 17 40]
 [92 60 22 95]]


array([[92, 60, 22, 95],
       [42, 84, 17, 40],
       [58, 79, 12, 85],
       [49, 13, 99, 75],
       [92, 23, 34, 95],
       [67, 39, 68, 79]])

### **np.put**
The np.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

In [58]:
print(' before change a:', a)

np.put(a, [0, 1], [110, 530])

print('after change a:', a)


 before change a: [86 96 63 51 48 21 96 80 57 51 45 86  5 71 15]
after change a: [110 530  63  51  48  21  96  80  57  51  45  86   5  71  15]


### **np.delete**
The np.delete() function returns a new array with the deletion od sub-arrays along with the mentioned axis.

In [60]:
# code
print('before delete a:', a)

np.delete(a, [0, 1])


before delete a: [110 530  63  51  48  21  96  80  57  51  45  86   5  71  15]


array([63, 51, 48, 21, 96, 80, 57, 51, 45, 86,  5, 71, 15])

### **Set Function**
- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [61]:
# np.union1d
n = np.array([1, 2, 3, 4, 5])
m = np.array([3, 4, 5, 6, 7])

np.union1d(n, m)


array([1, 2, 3, 4, 5, 6, 7])

In [62]:
# np.intersect1d
np.intersect1d(n, m)


array([3, 4, 5])

In [63]:
# np.setdiff1d
np.setdiff1d(n, m)


array([1, 2])

In [64]:
# setxor1d
np.setxor1d(n, m)


array([1, 2, 6, 7])

In [67]:
# np.in1d
np.in1d(n, 5)


array([5])

In [68]:
n[np.in1d(n, 5)]


array([5])

### **np.clip**
np.clip() function is used to clip (limit) the values in an array.

In [70]:
# code
print('a:', a)

np.clip(a, a_min=25, a_max=80)


a: [110 530  63  51  48  21  96  80  57  51  45  86   5  71  15]


array([80, 80, 63, 51, 48, 25, 80, 80, 57, 51, 45, 80, 25, 71, 25])