In [2]:
import numpy as np

In [3]:
l = [1,2,3,4]

In [5]:
ar = np.array(l)

In [6]:
type(ar)

numpy.ndarray

In [7]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [8]:
np.asarray(l)

array([1, 2, 3, 4])

In [9]:
a= [2,3,4]

In [10]:
np.asanyarray(a)

array([2, 3, 4])

In [11]:
b = np.matrix(l)

In [12]:
b

matrix([[1, 2, 3, 4]])

In [13]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [14]:
a = np.array(l)

In [15]:
a

array([1, 2, 3, 4])

In [16]:
c = a

In [17]:
c

array([1, 2, 3, 4])

In [18]:
c[0] = 100

In [19]:
c

array([100,   2,   3,   4])

In [20]:
a

array([100,   2,   3,   4])

In [21]:
d = np.copy(a)

In [22]:
d

array([100,   2,   3,   4])

In [23]:
a[1] = 400

In [24]:
a

array([100, 400,   3,   4])

In [25]:
np.fromfunction(lambda i, j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [27]:
np.fromfunction(lambda i, j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [28]:
itrerable = (i*i for i in range(5))

In [30]:
np.fromiter(itrerable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [31]:
np.fromstring('4,5', sep=',')

array([4., 5.])

DataType

In [32]:
l = [2,3,4,5,6]

In [33]:
ar = np.array(l)

In [34]:
ar

array([2, 3, 4, 5, 6])

find dimemsion, array, string and shaped

In [35]:
ar.ndim

1

In [36]:
ar2 = np.array([[1,2,3,4,5], [2,3,4,5]])

C:\Users\dhanr\AppData\Local\Temp\ipykernel_15028\2102885632.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar2 = np.array([[1,2,3,4,5], [2,3,4,5]])


In [37]:
ar.shape

(5,)

In [38]:
ar2.shape

(2,)

In [43]:
ar22 = np.array([(1.4,45,45), (23, 45, 66)])

In [44]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [45]:
ar22.dtype

dtype('float64')

always take integer in range

In [46]:
list(range(5))

[0, 1, 2, 3, 4]

arange use for float

In [47]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [49]:
list(np.arange(2.3, 5.6, .3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [50]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

produce array where every value is 0

In [51]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

Two Dimensional

In [52]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Three Dimensional crosses

how to read - we have 4 cross 2 and 3 such kind of matrix or arrays

In [53]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

Four Dimensional Matrix

how to define - we have 2 cross 3 and 3 such kind of matrix or arrays have 3 times

In [55]:
ar4 = np.zeros((3,4,2,3))

In [56]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [57]:
ar4.ndim

4

In [58]:
np.ones(4)

array([1., 1., 1., 1.])

In [59]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [61]:
on = np.ones((2,3,2))

In [62]:
on + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [63]:
on *4 

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

create empty array

In [64]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

identity matrix is square and diagonal is 1

In [65]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

take a data 2 to 4 and divide by 20

In [66]:
np.linspace(2,3,20)

array([2.        , 2.05263158, 2.10526316, 2.15789474, 2.21052632,
       2.26315789, 2.31578947, 2.36842105, 2.42105263, 2.47368421,
       2.52631579, 2.57894737, 2.63157895, 2.68421053, 2.73684211,
       2.78947368, 2.84210526, 2.89473684, 2.94736842, 3.        ])

produce 10 data and log every data

In [67]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [68]:
np.logspace(2,5,10, base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

Create random Data

randn -  generate data which mean or avg is zero and standard deviation is one


In [71]:
ar = np.random.randn(3,4)

In [70]:
import pandas as pd

In [72]:
pd.DataFrame(ar)

0         1         2         3
0  0.652758 -0.293740 -0.060278 -2.185937
1  0.490103  2.573327 -0.688367 -0.435412
2  0.518310  0.428333 -0.018488 -1.260511

rand - randomly produced

In [73]:
np.random.rand(3,4)

array([[0.20698512, 0.11766795, 0.05735193, 0.27589018],
       [0.54307369, 0.08397113, 0.94956485, 0.19306157],
       [0.59230507, 0.54204277, 0.85606679, 0.2456455 ]])

randint - always produce integer data between 1 to 10 and 3 by 4 matrix


In [74]:
np.random.randint(1,10,(3,4))

array([[7, 6, 3, 1],
       [8, 5, 1, 6],
       [3, 3, 4, 9]])

csv file with random data

In [76]:
pd.DataFrame(np.random.randint(1,10, (50, 20))).to_csv('test.csv')

In [77]:
arr = np.random.rand(3,4)

In [78]:
arr

array([[0.80286208, 0.33209701, 0.53777531, 0.07862325],
       [0.80864086, 0.8363764 , 0.26705151, 0.83705666],
       [0.46182275, 0.77957854, 0.70665558, 0.26092984]])

rearrange data

Always reshape data with fraction of multiplication of previous data

like 3,4 (previous data) = 3 * 4 =12 

now reshape data fraction of 12 like (6,2), (2,6),(4,3),(12,1)...

In [79]:
arr.reshape(6,2)

array([[0.80286208, 0.33209701],
       [0.53777531, 0.07862325],
       [0.80864086, 0.8363764 ],
       [0.26705151, 0.83705666],
       [0.46182275, 0.77957854],
       [0.70665558, 0.26092984]])

In [84]:
arr[1][1]

0.8363763993491765

In [87]:
arr[1,1:5]

array([0.8363764 , 0.26705151, 0.83705666])

In [88]:
arr = np.random.randint(1,100, (5,5))

In [89]:
arr

array([[35, 83, 81, 54, 24],
       [79, 73, 73, 88, 81],
       [92, 20, 16, 18, 27],
       [33, 53, 17, 14, 81],
       [70, 69, 47, 39, 52]])

In [90]:
arr>50

array([[False,  True,  True,  True, False],
       [ True,  True,  True,  True,  True],
       [ True, False, False, False, False],
       [False,  True, False, False,  True],
       [ True,  True, False, False,  True]])

In [91]:
arr[arr>50]

array([83, 81, 54, 79, 73, 73, 88, 81, 92, 53, 81, 70, 69, 52])

In [92]:
arr[2:4, [1,2]]

array([[20, 16],
       [53, 17]])

manupulate data

In [94]:
arr[0,0] = 5000

In [95]:
arr

array([[5000,   83,   81,   54,   24],
       [  79,   73,   73,   88,   81],
       [  92,   20,   16,   18,   27],
       [  33,   53,   17,   14,   81],
       [  70,   69,   47,   39,   52]])

adding two matrix

In [97]:
arr1 = np.random.randint(1,3, (3,3))
arr2 = np.random.randint(1,3, (3,3))

In [98]:
arr1

array([[1, 2, 2],
       [2, 2, 1],
       [1, 1, 2]])

In [99]:
arr2


array([[2, 1, 1],
       [2, 2, 2],
       [1, 2, 2]])

In [100]:
arr1 + arr2

array([[3, 3, 3],
       [4, 4, 3],
       [2, 3, 4]])

subtract array

In [101]:
arr1 - arr2

array([[-1,  1,  1],
       [ 0,  0, -1],
       [ 0, -1,  0]])

divide matrix


In [102]:
arr1/arr2

array([[0.5, 2. , 2. ],
       [1. , 1. , 0.5],
       [1. , 0.5, 1. ]])

multiply index matrix

In [103]:
arr1*arr2

array([[2, 2, 2],
       [4, 4, 2],
       [1, 2, 4]])

matrix multipllication

In [104]:
arr1@arr2

array([[8, 9, 9],
       [9, 8, 8],
       [6, 7, 7]])

In [105]:
arr1/0

C:\Users\dhanr\AppData\Local\Temp\ipykernel_15028\1510032488.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [106]:
arr1 + 100

array([[101, 102, 102],
       [102, 102, 101],
       [101, 101, 102]])

In [107]:
arr1**2

array([[1, 4, 4],
       [4, 4, 1],
       [1, 1, 4]], dtype=int32)

broadcasting

In [111]:
arr = np.zeros((4,4))

In [109]:
row = np.array([1,2,3,4])

In [110]:
row

array([1, 2, 3, 4])

In [112]:
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

not rotate bcz one dimensionala array need 2d array


In [114]:
row.T

array([1, 2, 3, 4])

In [115]:
col = np.array([[1,2,3,4]])

In [116]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [117]:
col.T+arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [118]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [120]:
arr1 = np.random.randint(1,4,(3,4))

square root

In [121]:
np.sqrt(arr1)

array([[1.73205081, 1.        , 1.        , 1.41421356],
       [1.        , 1.73205081, 1.        , 1.        ],
       [1.73205081, 1.73205081, 1.41421356, 1.73205081]])

exponent

In [122]:
np.exp(arr1)

array([[20.08553692,  2.71828183,  2.71828183,  7.3890561 ],
       [ 2.71828183, 20.08553692,  2.71828183,  2.71828183],
       [20.08553692, 20.08553692,  7.3890561 , 20.08553692]])

In [123]:
np.log10(arr1)

array([[0.47712125, 0.        , 0.        , 0.30103   ],
       [0.        , 0.47712125, 0.        , 0.        ],
       [0.47712125, 0.47712125, 0.30103   , 0.47712125]])