In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1,10,(3,4))

In [4]:
arr

array([[7, 1, 5, 3],
       [1, 3, 3, 8],
       [2, 5, 9, 6]])

In [5]:
arr.reshape(6,2)

array([[7, 1],
       [5, 3],
       [1, 3],
       [3, 8],
       [2, 5],
       [9, 6]])

Data convert in one dimension

In [6]:
arr.flatten()

array([7, 1, 5, 3, 1, 3, 3, 8, 2, 5, 9, 6])

In [7]:
arr1 = np.array([1,2,3,3,4])

In [8]:
arr1.ndim

1

One Dimension to two dimension

In [9]:
np.expand_dims(arr1, axis=1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [10]:
np.expand_dims(arr1, axis=0)

array([[1, 2, 3, 3, 4]])

In [11]:
arr

array([[7, 1, 5, 3],
       [1, 3, 3, 8],
       [2, 5, 9, 6]])

In [13]:
data = np.array([[1],[2],[3]])

In [14]:
data

array([[1],
       [2],
       [3]])

In [15]:
np.squeeze(data)

array([1, 2, 3])

In [16]:
arr1

array([1, 2, 3, 3, 4])

repeat element 3 times

In [17]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

rotate data with 2 place 

like - 1 goes 2th position and 2 goes 3th position 

In [19]:
np.roll(arr1,2)

array([3, 4, 1, 2, 3])

place 1D data in diagonal

In [20]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

binary operation

In [22]:
arr1 = np.random.randint(1,10,(3,4))

In [23]:
arr2 = np.random.randint(1,10,(3,4))

In [24]:
arr1

array([[8, 6, 6, 8],
       [9, 6, 1, 1],
       [8, 9, 5, 7]])

In [25]:
arr2

array([[6, 7, 5, 4],
       [2, 7, 5, 6],
       [7, 6, 4, 2]])

In [26]:
arr1+arr2

array([[14, 13, 11, 12],
       [11, 13,  6,  7],
       [15, 15,  9,  9]])

remainder

In [27]:
arr1%arr2

array([[2, 6, 1, 0],
       [1, 6, 1, 1],
       [1, 3, 1, 1]], dtype=int32)

negative all element


In [28]:
~arr1

array([[ -9,  -7,  -7,  -9],
       [-10,  -7,  -2,  -2],
       [ -9, -10,  -6,  -8]], dtype=int32)

string function

In [33]:
arr = np.array(['sudh','ram'])

In [34]:
np.char.upper(arr)

array(['SUDH', 'RAM'], dtype='<U4')

In [35]:
np.char.title(arr)

array(['Sudh', 'Ram'], dtype='<U4')

In [36]:
np.char.capitalize(arr)

array(['Sudh', 'Ram'], dtype='<U4')

mathematical

In [37]:
arr1

array([[8, 6, 6, 8],
       [9, 6, 1, 1],
       [8, 9, 5, 7]])

In [38]:
np.sin(arr1)

array([[ 0.98935825, -0.2794155 , -0.2794155 ,  0.98935825],
       [ 0.41211849, -0.2794155 ,  0.84147098,  0.84147098],
       [ 0.98935825,  0.41211849, -0.95892427,  0.6569866 ]])

In [40]:
np.cos(arr1)

array([[-0.14550003,  0.96017029,  0.96017029, -0.14550003],
       [-0.91113026,  0.96017029,  0.54030231,  0.54030231],
       [-0.14550003, -0.91113026,  0.28366219,  0.75390225]])

In [41]:
np.power(arr1,2)

array([[64, 36, 36, 64],
       [81, 36,  1,  1],
       [64, 81, 25, 49]], dtype=int32)

In [42]:
np.mean(arr1)

6.166666666666667